version: 2
jobs:
  build:
    docker: #
      - image: circleci/node:8.12.0
    steps:
      - checkout # check out the code in the project directory
      - run: npm i
      - run: npm run test
      - run: npm run posttest
